import { Button, Link } from '@material-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import SimpleCard from '../components/SimpleCard'
import Footer from '../elements/Footer'
import dbConnect from '../lib/dbConnect'
import Movie from '../models/Movie'
import styles from '../styles/Home.module.css'

export default function Home({ movies }) {
  console.log(movies)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Movies
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <Link href="/new">
          <Button variant="outlined" color="primary" style={{ marginTop: '20px', marginBottom: '20px' }}>
            CREATE
          </Button>
        </Link>
        {
          movies.map(({ _id, name, description }) =>

          (
            <Link key={_id} href={`/${_id}`} style={{ textDecoration: 'none' }} >
              <SimpleCard key={_id} id={_id} title={name} description={description} />
            </Link>)
          )
        }

      </main>

      <Footer/>

    </div>
  )
}

export async function getServerSideProps() {
  try {
    await dbConnect()
    console.log("Successfully connected!")
    const res = await Movie.find({});
    // formating to pure JSON before sending to client side
    const movies = res.map((doc) => {
      const movie = doc.toObject()
      movie._id = `${movie._id}`
      return movie
    })
    console.log(res)
    return { props: { movies: movies } }
  } catch (error) {
    console.log(error)
    return { props: { success: false, error: "Error while getting data" } }
  }
}